### ISSUE TITLE
'Failed to initialize memory mapped mode

### ISSUE THREAD

**Issue by silexxx** [abhirooptalasila/AutoSub#1]
speech/__init__.py", line 38, in __init__
    raise RuntimeError("CreateModel failed with '{}' (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status))
RuntimeError: CreateModel failed with 'Failed to initialize memory mapped model.' (0x3000)

**Comment by abhirooptalasila** [comment]
Hi 
Could you please detail the steps you took leading up to this issue?
[Here's](https://discourse.mozilla.org/t/deepspeech-0-7-3-on-windows-failed-to-initialize-memory-mapped-model/61561) a similar issue on Mozilla Discourse. Is this similar to what you're facing?

**Comment by silexxx** [comment]
yes I found the issue the mentioned thread helped me thank you so much for the quick response.

**Comment by silexxx** [comment]
And I am running this code:
import os
import speech_recognition as sr

filename="1"
command2mp3 = f"ffmpeg -i {filename}.mp4 {filename}.mp3"
command2wav = f"ffmpeg -i {filename}.mp3 {filename}.wav"

os.system(command2mp3)
os.system(command2wav)

filename=f"{filename}.wav"

r=sr.Recognizer()

with sr.AudioFile(filename) as source:
    audio_data=r.record(source)
    text=r.recognize_google(audio_data)
    print(text)


And it is giving me the speech text from the wave file pretty good can you tell me how to make a subtitle file out of that text

**Comment by abhirooptalasila** [comment]
Hi
Can you tell me what the WAV file is in this context?
 
writeToFile.py handles writing the subtitles to the SRT file. It recieves the time stamps and text for each spoken sentence from main.py
Please go through the README properly to understand the flow of execution.

**Comment by silexxx** [comment]
WAV sound format and thank you I found the way to do them
