### ISSUE TITLE
HI abhiroop! i got an error while running your code please help me.

### ISSUE THREAD

**Issue by rajshahdev** [abhirooptalasila/AutoSub#11]
i encountered string to float error i don't how to fix this. i am really thankful if you reply to this thread.
![error](https://user-images.githubusercontent.com/48146258/105172680-fe2a7b00-5b45-11eb-8f91-e53d4b746e4d.JPG)

**Comment by abhirooptalasila** [comment]
Hi
You'll need to replace `split("/")` with `split("\")` in _main.py_ since you're on Windows. 
You can go through #9 just in case

**Comment by rajshahdev** [comment]
thank you so much for replying i'll try and let you know.
