### ISSUE TITLE
Amazing! Although the results are not that accurate.

### ISSUE THREAD

**Issue by fintechee** [abhirooptalasila/AutoSub#12]
Amazing! Although the results are not that accurate.

How can I improve the accuracy? Many thanks.

https://www.youtube.com/watch?v=TOQwUISm6fw

1
00:00:00,10 --> 00:00:00,95
one

2
00:00:01,55 --> 00:00:07,10
this visconti to learn how to go at the vices

3
00:00:08,20 --> 00:00:14,80
who to open that automatic aridius in

4
00:00:14,95 --> 00:00:21,50
and this idea will guide us how to add indicator automatical

5
00:00:21,95 --> 00:00:26,50
and we will go and newton

6
00:00:26,90 --> 00:00:34,0:
and we were used in piraguas moreale indication

7
00:00:34,40 --> 00:00:43,45
starting first of all we need to add one more premature

8
00:00:44,25 --> 00:00:53,80
the primates named yes bury in the morning added coelesti special the period wooing happy

9
00:00:54,15 --> 00:00:59,70
and we will get the primitive party by using dislike

10
00:01:02,60 --> 00:01:07,25
and it the new eenamost cat indicated handle

11
00:01:08,25 --> 00:01:10,80
to get hard

12
00:01:12,25 --> 00:01:15,15
i remember very honour

13
00:01:15,75 --> 00:01:20,0:
if the specific indicator doesn't because

14
00:01:20,75 --> 00:01:30,15
then his deep we create a new one force and then returned the handle of the new indicator

15
00:01:30,50 --> 00:01:31,90
if

16
00:01:32,40 --> 00:01:43,50
the specific indicator has existed then this peril return the handle of the specifically indicate

17
00:01:46,30 --> 00:01:55,50
and handles into idea holes to hide in fine the chatterment

18
00:01:55,70 --> 00:01:59,30
so hand is very important information 

19
00:01:59,55 --> 00:02:05,70
we will stop the return better to this very

20
00:02:06,40 --> 00:02:17,80
don't forget to go estimable after wives lorrainese how it works

21
00:02:18,10 --> 00:02:19,40
by ronald

22
00:02:24,20 --> 00:02:26,35
we just need to copy 

.............

**Comment by abhirooptalasila** [comment]
Hi
You can try:
 - Recognising on just the speech audio without the background music since the former is very faint (in terms of volume)
 - Tweak the `smoothing_window` and `weight` params [here](https://github.com/abhirooptalasila/AutoSub/blob/5444d9ab56b03c3d36eaedfaf9fcb9dfc63a3770/autosub/segmentAudio.py#L197) and see if it helps

**Comment by fintechee** [comment]
@abhirooptalasila 
Hi, thank you for your fast response.
I will try the parameters. But actually, other autosub online service(such as Veed) can recognize the speech audio even there is background music.
Anyway, many thanks for your suggestion.
