### ISSUE TITLE
Split overly long transcript segments

### ISSUE THREAD

**Issue by Rillke** [abhirooptalasila/AutoSub#13]
Currently it's easily possible to receive cues with 340 characters or more. Amara.org suggests a maximum of 42 per line.

[DeepSpeech provides](https://deepspeech.readthedocs.io/en/latest/Python-API.html#native_client.python.Model.sttWithMetadata) timing data for each individual character, therefore the word duration and start can be calculated (see [client.py](https://deepspeech.readthedocs.io/en/latest/Python-Examples.html)) and a clean split is possible (possibly breaking the sentence but still better than 340 chars and better than having to support different grammars.)

Here is what their sample script already provides:
```json
{
  "transcripts": [
    {
      "confidence": -44.99164581298828,
      "words": [
        {
          "word": "ja",
          "start_time": 0.36,
          "duration": 0.3
        },
        {
          "word": "meine",
          "start_time": 0.7,
          "duration": 0.22
        },
        {
          "word": "sehr",
          "start_time": 0.96,
          "duration": 0.14
        },
        {
          "word": "verehrten",
          "start_time": 1.12,
          "duration": 0.32
        },
        {
          "word": "damen",
          "start_time": 1.48,
          "duration": 0.22
        },
        {
          "word": "und",
          "start_time": 1.74,
          "duration": 0.12
        },
        {
          "word": "herren",
          "start_time": 1.9,
          "duration": 0.5
        },
        {
          "word": "liebe",
          "start_time": 2.48,
          "duration": 0.32
        },
        {
          "word": "frau",
          "start_time": 2.86,
          "duration": 0.48
        },
        {
          "word": "versorgen",
          "start_time": 3.38,
          "duration": 0.42
        }
      ]
    },
    {
      "confidence": -45.583431243896484,
      "words": [
        {
          "word": "ja",
          "start_time": 0.36,
          "duration": 0.3
        },
```

The idea is to find a good point for splitting, which can be a weighted decision: the closer we come to the desired splitting point, the less time between words is required for a split, if a split is required/ desired.

**Comment by abhirooptalasila** [comment]
Do you have a specific way of checking for the nearest word to split based on the number of words already processed?
