### ISSUE TITLE
Numpy <= 1.17.0 required? (I have 1.20.0)

### ISSUE THREAD

**Issue by fluttershift** [abhirooptalasila/AutoSub#18]
During the installation of requirements I get,

deepspeech 0.9.3 has requirement numpy<=1.17.0,>=1.14.5, but you'll have numpy 1.20.0 which is incompatible.

**Comment by abhirooptalasila** [comment]
The NumPy requirements are changing with every new DeepSpeech release. It's hard to maintain compatibility across different platforms. Hence, I removed the version numbers in `requirements.txt`. The best way to solve this is to use the NumPy version suggested by pip while installing and replace it in `requirements.txt`.
