### ISSUE TITLE
Older CPU's get Illegal instruction with Deepspeech binary due to missing AVX instructions, I have recompiled and replaced the binary.. 

### ISSUE THREAD

**Issue by abclution** [abhirooptalasila/AutoSub#20]
So, long standing issue/non issue due to upstream (tensorflow) decisions when packaging the binaries to require AVX extensions. Anyways, 2 hours later I have recompiled DeepSpeech and have verified it working on my machine. 

Buut, even after replacing the binary AutoSub/sub/bin/deepspeech I still get the illegal instruction.

Where exactly can I replace the binary to use the one I compiled that will work on my cpu? Thank you.

**Comment by abclution** [comment]
For anyone who runs into this I solved it by updating the pip installed .so (shared object) with the one I compiled.

Replace 
AutoSub/sub/lib/python3.7/site-packages/deepspeech/lib/libdeepspeech.so

With the one I compiled.

**Comment by abhirooptalasila** [comment]
Does it work now or are you still facing an issue?

**Comment by shasheene** [comment]
> Does it work now or are you still facing an issue?

He said in his second comment that he solved it. By copying in the shared object which he compiled to overwrite the one that was installed using PIP.

This issue can be closed. I suggest giving the issue a "question" label.
