### ISSUE TITLE
ImportError: DLL load failed while importing _impl: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by HafMann** [abhirooptalasila/AutoSub#22]
Hi, after I installed Autosub I always get this error message when I try to run the program "ImportError: DLL load failed while importing _impl: A dynamic link library (DLL) initialization routine failed." Could anyone tell me how to fix this?

**Comment by abhirooptalasila** [comment]
Check if [this](https://github.com/tensorflow/tensorflow/issues/23683#issuecomment-532522740) resolves your issue.

**Comment by HafMann** [comment]
It didn't work.

**Comment by abhirooptalasila** [comment]
I'm gonna need more info about your setup, how you installed DeepSpeech, TF and what you're trying to do.

**Comment by HafMann** [comment]
Do I have to install TF separately? or was it included in Autosub?

**Comment by HafMann** [comment]
I use Python 3.8 from Microsoft Store by the way

**Comment by abhirooptalasila** [comment]
So you're not using Conda? If your default python env doesn't have TF installed, it will be installed by DeepSpeech. I think there is some kind of a version mismatch. Please check the DeepSpeech docs once. And, if that doesn't work, uninstall your current python and install via a normal Python installer, or better, use WSL.

**Comment by HafMann** [comment]
Could you give me instructions with which commands should I use when i try with Conda? If they are different.

**Comment by HafMann** [comment]
P.S. Should I run the command line as Administrator?

**Comment by abhirooptalasila** [comment]
I won't be able to go so much in detail. It's pretty straightforward if you follow the DeepSpeech [docs](deepspeech.readthedocs.io/).
