### ISSUE TITLE
processing mandarin Chinese video error

### ISSUE THREAD

**Issue by yaojingzhe** [abhirooptalasila/AutoSub#25]
Hi Dear author:

When I process audio to srt with mandarin Chinese video, the following error occurred:
First time with same video:

> Traceback (most recent call last):
>   File "C:\Python\AutoSub\autosub\main.py", line 139, in <module>
>     main()
>   File "C:\Python\AutoSub\autosub\main.py", line 129, in main
>     ds_process_audio(ds, audio_segment_path, file_handle)
>   File "C:\Python\AutoSub\autosub\main.py", line 68, in ds_process_audio
>     write_to_file(file_handle, infered_text, line_count, limits)
>   File "C:\Python\AutoSub\autosub\writeToFile.py", line 24, in write_to_file
>     d = str(datetime.timedelta(seconds=float(limits[1])))
> IndexError: list index out of range

second time with same video:

> Traceback (most recent call last):
>   File "C:\Python\AutoSub\autosub\main.py", line 139, in <module>
>     main()
>   File "C:\Python\AutoSub\autosub\main.py", line 129, in main
>     ds_process_audio(ds, audio_segment_path, file_handle)
>   File "C:\Python\AutoSub\autosub\main.py", line 68, in ds_process_audio
>     write_to_file(file_handle, infered_text, line_count, limits)
>   File "C:\Python\AutoSub\autosub\writeToFile.py", line 32, in write_to_file
>     file_handle.write(inferred_text + "\n\n")
> UnicodeEncodeError: 'gbk' codec can't encode character '\udce4' in position 18: illegal multibyte sequence

It’s well done with en video, I can get srt.

_system: ubuntu 20.04
python: 3.7.1 3.8.8 and 3.9.4_

Thank you very much for your reply.

**Comment by abhirooptalasila** [comment]
Hi
Are you using your own Mandarin model and scorer files? 
I'm not sure why the first error occurs. Can you put `print(limits)` just above line 24 in write_to_file?
For the second one, I think it's because the file is opened in UTF-8 by default. Change that to Unicode to support Mandarin letters.

**Comment by yaojingzhe** [comment]
Dear author:

Would you please send me the files which you modified and changed that to Unicode to support Mandarin letters? I mean these code support Mandarin model and scorer files. I dont understand python code at all. 

or which information should I provide to you?

by the way, can I run your code on windows with python 3.8?

thanks very much.

my email: s0957@163.com

**Comment by yaojingzhe** [comment]
Dear author:

Would you please send me the files which you modified and changed that to Unicode to support Mandarin letters? I mean these code support Mandarin model and scorer files. I dont understand python code at all. 

or which information should I provide to you?

by the way, can I run your code on windows with python 3.8?

thanks very much.

**Comment by abhirooptalasila** [comment]
That's not feasible. I don't have the model files and neither have I worked on Mandarin models before. My comment was just a suggestion. 
I don't have the time to go through this in detail. 
I can help you with any specific issues in my code but I can't do your work for you. 

Yes, this script works on Windows too.
