### ISSUE TITLE
Problem using Chinese Acoustic models

### ISSUE THREAD

**Issue by WanderingCoder-Omen** [abhirooptalasila/AutoSub#26]
Hey Abhiroop great work on the AutoSub. It works flawlessly with the English acoustic models. However I was trying to use the experimental Chinese acoustic models which have been released and faced some issues. I guess there are some issues with the encoding part of it when the subtitle file is being written. Can you please check ? 
![AutoSub Error](https://user-images.githubusercontent.com/60088552/119819240-c8d7d480-bf0d-11eb-98a3-c2575691c6e3.JPG)
I have tried to change the encoding to utf-8 but it hasn't helped.

**Comment by abhirooptalasila** [comment]
Hi 
Thank you!
Is [this](https://github.com/abhirooptalasila/AutoSub/blob/ee7fcb1815c173eab626b535306a9405cbd5e33c/autosub/main.py#L135) where you changed the encoding?
Maybe [this](https://stackoverflow.com/questions/62656579/why-im-getting-unicodeencodeerror-charmap-codec-cant-encode-character-u2) will help.

**Comment by yisishoujo** [comment]
i made it work by add the following line after `split_inferred_text = ` in `main.py`
`split_inferred_text = split_inferred_text.encode('utf-8', errors='surrogateescape').decode('utf-8')`
but the output result is terrible, only a few words makes sense, very far from meaningful chinese sentence.

**Comment by abhirooptalasila** [comment]
I will update the entire repo to use Whisper. Maybe then it'll be better. Thanks!
