### ISSUE TITLE
Is it impossible to recognize in another language?

### ISSUE THREAD

**Issue by kdrkdrkdr** [abhirooptalasila/AutoSub#28]
Is it impossible to recognize in another language?

I hope the caption file comes out in Japanese.

I put a video of the conversation in Japanese and it came out in English, is there a way to modify it?

or.. is there any japaense model files?

**Comment by abhirooptalasila** [comment]
Hi
Yes, you could have a look at some official or community models. There's a thread on the Deepspeech discourse which collates all public models.

**Comment by shasheene** [comment]
I believe this is the thread: https://discourse.mozilla.org/t/links-to-pretrained-models/62688

Be aware there are different versions of DeepSpeech models supposedly. I am yet unaware of any Japanese language model.

I am thinking of training one using eg, https://github.com/laboroai/LaboroTVSpeech but I hope somebody does it first and releases it.

**Comment by abhirooptalasila** [comment]
Yes. Model training is actually a very tedious process if you don't have the necessary compute on hand. 
I dabbled with both fine-tuning and training from scratch, with not-so-great improvements. 
So, if you can wait, you should keep an eye out for models trained by reputed groups.

**Comment by shasheene** [comment]
For what it's worth, I have a GTX 970 for gaming, which may be sufficient for compute.

But yes, keeping an eye out for models by reputed groups seems like the best idea.

**Comment by abhirooptalasila** [comment]
That's okay for quick prototyping but not at all enough to train models like DeepSpeech. 
For example, I was adapting DeepSpeech for the Indian accent across multiple regional languages, the dataset was around 50 GB (which is less according to the DeepSpeech maintainers) and training on a 2080Ti took almost 10 days. We had to rent remote servers. I didn't have in-depth knowledge about DeepSpeech and had to do very small changes to batch size/augmentations/layer sizes etc.
