### ISSUE TITLE
Illegal instruction when trying to perform an operation on a mp4 file

### ISSUE THREAD

**Issue by gabriellluz** [abhirooptalasila/AutoSub#3]
I'm getting an error when trying to perform autosub on a mp4 file:

`python3 main.py --model "/media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/autosub/deepspeech-0.8.2-models.pbmm" --scorer "/media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/autosub/deepspeech-0.8.2-models.scorer" --file "test.mp4"`

The error message:
Illegal instruction (core dumped)

I think my computer is too old. I have an Intel integrated graphics card. Maybe that could be the reason? I'm buying a new video card next month and I'll try to use it again if that's the problem. 
If it works, I'll consider making a kivy GUI for it.

**Comment by abhirooptalasila** [comment]
Hey
DeepSpeech works fine without a graphics card. One of these two approaches _should_ solve your issue:
1) What's your processor and RAM? I came across [this](https://discourse.mozilla.org/t/cant-transcribe-illegal-instruction-core-dumped/51925) issue. If the processor is too old, it’s very likely that it doesn’t support AVX/AVX2. Refer [this](https://github.com/mozilla/DeepSpeech/issues/1322), and [this](https://github.com/mozilla/DeepSpeech/issues/1135).
2) Do you have Sox and FFmpeg installed? Sox shouldn't be necessary but try after installing it. For Ubuntu, you can do:
`sudo apt-get install -y sox`

Just as a sanity check, double-check your argument paths, please.

**Comment by gabriellluz** [comment]
Yep, unfortunately my processor is too old. I'm buying a new one from China. It'll takes something. I'll have to postpone using your application but I intend to make a Kivy GUI out of this. Thanks a lot.
