### ISSUE TITLE
Create vtt, srt, txt files by default (drop the --vtt option)

### ISSUE THREAD

**Issue by shasheene** [abhirooptalasila/AutoSub#33]
Currently AutoSub has the following command-line interface:

```
usage: main.py [-h] --file FILE [--vtt]

AutoSub

optional arguments:
  -h, --help   show this help message and exit
  --file FILE  Input video file
  --vtt        Output a vtt file with cue points for individual words instead
               of a srt file

```

The `--vtt` option is used to **switch** between outputting a SRT file to outputting VTT file.

But given it's the inference part that takes the bulk of the execution time and the output subtitle file format doesn't take much time and uses very little disk space then rerunning the entire inference again just to get a VTT file is inefficient. It makes more sense just to create the VTT and SRT by default.

Also, AutoSub is well-placed to output a transcript of the input at the same time. Indeed, I saw an [AutoSub fork that did just that](https://github.com/qlchan24/AutoSub/commits/master).

**So, I suggest replacing `--vtt` with a `--format` option that the user can _restrict_ the generated file formats, but by default it _should_ create all formats: VTT, SRT, _and_ a TXT transcript.**

I am happy to do the work and make a Pull Request. Are you happy with this approach?

**Comment by abhirooptalasila** [comment]
Hey
This looks good. Please go ahead!
