### ISSUE TITLE
Creating GitHub Organization and possibly changing project name

### ISSUE THREAD

**Issue by shasheene** [abhirooptalasila/AutoSub#38]
Ideally this project would be developed under a GitHub organization (but it's definitely not required).

The Autosub organization (https://github.com/autosub) namespace is already taken, and as you may know there's an unrelated (abandoned) project called "autosub" that uses the same name: https://github.com/agermanidis/autosub

Ideally you'd get that organization namespace but I don't think it's possible given there's no contact information.

How about renaming this project "AutoSubs" (or "AutoSubtitler") and registering https://github.com/AutoSubs (or https://github.com/AutoSubtitler)? I prefer "AutoSubs". Another option would be to keep the name "AutoSub" but register a different organization.

I think the GitHub organization domain would help with the growth of the project. But again, the change is definitely not required.

(Feel free to close this issue as WONTFIX, if you'd like)

**Comment by yash-fn** [comment]
AutoSubtitler will probably get more hits on a search engine if you want to consider marketing potential haha. But yeah AutoSubs is good too.
