### ISSUE TITLE
How to train models by ourselves and do we need to modify the code if we want to use GPU?

### ISSUE THREAD

**Issue by Snow9666** [abhirooptalasila/AutoSub#40]
Hi,
I just want to know how to train models by ourselves and do we need to modify the code if we want to use GPU？

**Comment by yash-fn** [comment]
No. Don't need to modify code. Best way is to use docker. you have docker? otherwise just make sure to use gpu pip requirements file.

**Comment by yash-fn** [comment]
to train model probably refer to the deepspeech documentation from Mozilla. This is essentially a wrapper for that project to make it usable to subtitle things. Thus any model trained for deepspeech can be used for this project since its essentially just deepspeech.
