### ISSUE TITLE
i cant pass this stip " $ source sub/bin/activate  "

### ISSUE THREAD

**Issue by maloadjav** [abhirooptalasila/AutoSub#43]
the error  say that "  source " is unknow  command .

people said that  because   it  s   unix command and i  use  window  10

so how to solve this problem ?

thank you so much

**Comment by maloadjav** [comment]
it  on the installation s section 

Installation

    Clone the repo. All further steps should be performed while in the AutoSub/ directory

    $ git clone https://github.com/abhirooptalasila/AutoSub
    $ cd AutoSub

    Create a pip virtual environment to install the required packages

    $ python3 -m venv sub
    $ source sub/bin/activate                    <=================================
    $ pip3 install -r requirements.txt

**Comment by abhirooptalasila** [comment]
Hi
A simple read-through of the [docs](https://docs.python.org/3/library/venv.html) would have solved this for you. 


Platform | Shell | Command to activate virtual environment
-- | -- | --
POSIX | bash/zsh | $ source <venv>/bin/activate
  | fish | $ source <venv>/bin/activate.fish
  | csh/tcsh | $ source <venv>/bin/activate.csh
  | PowerShell Core | $ <venv>/bin/Activate.ps1
Windows | cmd.exe | C:\> <venv>\Scripts\activate.bat
  | PowerShell | PS C:\> <venv>\Scripts\Activate.ps1
