### ISSUE TITLE
i think i have completely install it but i need help  .i am very...

### ISSUE THREAD

**Issue by maloadjav** [abhirooptalasila/AutoSub#45]
How-to example

    Make sure the model and scorer files are in the root directory. They are automatically loaded
    After following the installation instructions, you can run autosub/main.py as given below. The --file argument is the video file for which SRT file is to be generated

    $ python3 autosub/main.py --file ~/movie.mp4

-------------------------------------------------------

 1 i dont understand what is root directory  ? it is *****/autosub  ??  or somewhere else ?

2 after  i download deepspeech and i think i finally   can install this program  but i got so many error .

its hard to explain but it lookalike this program try to sub  your    tut  document.

what i am worng here.

**Comment by maloadjav** [comment]
[url=https://www.img.in.th/image/wO0mBE][img]https://www.img.in.th/images/c617aee4dc2b84bb55b9c29c55345951.jpg[/img][/url]
[url=https://www.img.in.th/image/wO0bGa][img]https://www.img.in.th/images/06d62ad48e7af4c6d170363dd8dfac98.jpg[/img][/url]

**Comment by maloadjav** [comment]
[img]https://www.img.in.th/images/c617aee4dc2b84bb55b9c29c55345951.jpg[/img]
[img]https://www.img.in.th/images/06d62ad48e7af4c6d170363dd8dfac98.jpg[/img]

**Comment by abhirooptalasila** [comment]
Yes, the model files need to be in the folder that you cloned this repo into. 
Why are you coying the attached text into the CLI? You just need to copy the commands after the `$` character.
Also, apt-get is a Linux command. Please use windows appropriate commands.
