### ISSUE TITLE
[Feature] GPU support

### ISSUE THREAD

**Issue by shravanshetty1** [abhirooptalasila/AutoSub#5]
Love the project, would it be too difficult to add gpu support? Planning on using this on production!

**Comment by abhirooptalasila** [comment]
Hi
Thanks! You could just install DeepSpeech's GPU package. Everything else will remain the same.
`$ pip3 install deepspeech-gpu`
Refer [this](https://deepspeech.readthedocs.io/en/v0.9.1/) and [this](https://deepspeech.readthedocs.io/en/v0.9.1/SUPPORTED_PLATFORMS.html) for details on platform support.
