### ISSUE TITLE
[Question] Dealing with background noise/music

### ISSUE THREAD

**Issue by shravanshetty1** [abhirooptalasila/AutoSub#6]
Any thoughts?
https://github.com/tyiannak/pyAudioAnalysis - says it can detect unkown sounds and has speaker diarization.
Can it use speaker diarization to extract only vocals and ignore other sources of sound?
Also if 2 people are speaking having speaker diarization would be great

**Comment by abhirooptalasila** [comment]
I'll need to go through it once. This currently just splits based on speech and doesn't distinguish between speakers. Other sources like music are automatically ignored.
