### ISSUE TITLE
Cannot import logger

### ISSUE THREAD

**Issue by 9588** [abhirooptalasila/AutoSub#67]
```docker run --volume=`pwd`input:/input --name autosub autosub --file /input/video.mp4``` encounter an error of 

> Traceback (most recent call last):
  File "autosub/main.py", line 8, in <module>
    from . import logger
ImportError: cannot import name 'logger'

**Comment by amir28** [comment]
I found a workaround. after git clone do `git revert 76144f85b3daf559277c612a16a630bbebb35384` that will undo [this commit](https://github.com/abhirooptalasila/AutoSub/commit/76144f85b3daf559277c612a16a630bbebb35384)
