### ISSUE TITLE
Problem running on Mac OS X Moterey

### ISSUE THREAD

**Issue by PacoH** [abhirooptalasila/AutoSub#69]
I installed everything using `commit 0d38535a7511d81a126dcd33e4b8e0922585b011` and created a virtualenv project as suggested. When I tried to run `autosub/main.py` I got:

	Traceback (most recent call last):
	  File "/Users/user/python virtualenvs/AutoSub/AutoSub/autosub/main.py", line 8, in <module>
		from . import logger
	ImportError: attempted relative import with no known parent package

I changed `from . import logger` to `import logger` and got:
	Traceback (most recent call last):
	  File "/Users/user/python virtualenvs/AutoSub/AutoSub/autosub/main.py", line 11, in <module>
		import numpy as np
	ModuleNotFoundError: No module named 'numpy'

I deactivated the virtualenv project and tried to install `numpy`––`python3 -m pip install --user numpy`––and got:

	Requirement already satisfied: numpy in /usr/local/lib/python3.10/site-packages (1.23.2)

I verified that `numpy` is in that directory.

At this point there is no point in continuing. I see there are instructions for building and running `autosub` using `Docker`. This is not an option for me so how can I procede in OS X?

**Comment by abhirooptalasila** [comment]
Hi
Are you using the Apple Silicon Macs? If yes, then Autosub won't work for you as DeepSpeech/Coqui are not compiled for ARM.

**Comment by PacoH** [comment]
Model Identifier:	iMac19,1
Processor Name:	6-Core Intel Core i5

**Comment by abhirooptalasila** [comment]
Hey
Were you able to get it to work?
