### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by tawhidkhn63** [abhirooptalasila/AutoSub#9]
Hello could you let me know how to install and run your program on windows. I am on the step where I did "pip3 install -r requirements.txt" and I got the following error.

            ERROR: Cannot install -r requirements.txt (line 4) and numpy==1.18.1 because these package versions have conflicting 
            dependencies.
            
            The conflict is caused by:
                The user requested numpy==1.18.1
                deepspeech 0.8.2 depends on numpy<=1.17.0 and >=1.14.5
            
            To fix this you could try to:
            1. loosen the range of package versions you've specified
            2. remove package versions to allow pip attempt to solve the dependency conflict
            
            ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by abhirooptalasila** [comment]
I think DeepSpeech dependencies were updated. Just replace `numpy==1.18.1` with `numpy` in _requirements.txt_ and try again.

**Comment by tawhidkhn63** [comment]
Ok I did what you told me then got this error. I'm running python 3.7 by the way.

            Collecting numpy
              Using cached numpy-1.17.0-cp37-cp37m-win_amd64.whl (12.8 MB)
            Installing collected packages: numpy, six, scipy, joblib, tqdm, scikit-learn, python-dateutil, pyparsing, pydub, kiwisolver, 
            deepspeech, Cython, cycler
            ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour 
            is the source of the following dependency conflicts.
            moviepy 1.0.3 requires numpy>=1.17.3; python_version != "2.7", but you have numpy 1.17.0 which is incompatible.
            audioconverter 0.3.0 requires pydub<1.0.0,>=0.24.1, but you have pydub 0.23.1 which is incompatible.
            Successfully installed Cython-0.29.21 cycler-0.10.0 deepspeech-0.8.2 joblib-0.16.0 kiwisolver-1.2.0 numpy-1.17.0 pydub- 
            0.23.1 pyparsing-2.4.7 python-dateutil-2.8.1 scikit-learn-0.21.3 scipy-1.4.1 six-1.15.0 tqdm-4.44.1

I then followed the rest of the instructions and tried to run an example mp4 and got this error:

            C:\Users\tawhid khan\AutoSub>python autosub/main.py --model /deepspeech-0.8.2-models.pbmm --scorer 
            /deepspeech-0.8.2-models.scorer --file "C:\Users\tawhid khan\Desktop\ocunote\ex1.mp4"
            AutoSub v0.1
            
            TensorFlow: v2.2.0-24-g1c1b2b9dd9
            DeepSpeech: v0.8.2-0-g02e4c762
            Not found: NewReadOnlyMemoryRegionFromFile failed to Create/Open: /deepspeech-0.8.2-models.pbmm : The system 
            cannot find the file specified.
            ; No such file or directory
            Traceback (most recent call last):
              File "autosub/main.py", line 130, in <module>
                main()
              File "autosub/main.py", line 89, in main
                ds = Model(ds_model)
              File "C:\Users\tawhid khan\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech\__init__.py", line 
             38, in __init__
                raise RuntimeError("CreateModel failed with '{}' 
                 (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status))
            RuntimeError: CreateModel failed with 'Failed to initialize memory mapped model.' (0x3000)


I have downloaded the pbmm and scorer files into main autosub directory like in this picture. It would be great if you could help me thanks. 


![image](https://user-images.githubusercontent.com/39498885/103431102-fc9a1280-4b98-11eb-8de6-e4955adde045.png)

**Comment by tawhidkhn63** [comment]
Oh never mind I had to specify the full path to the model and scorer like this:

          python autosub/main.py --model "C:\Users\tawhid khan\AutoSub\deepspeech-0.8.2-models.pbmm" --scorer "C:\Users\tawhid khan\AutoSub\deepspeech-0.8.2-models.scorer" --file "C:\Users\Public\ocunote\ex2.mp4"

**Comment by tawhidkhn63** [comment]
I tried running a 5min mp4 file and I think the program worked as shown by the output:

![image](https://user-images.githubusercontent.com/39498885/103431209-9f9f5c00-4b9a-11eb-953d-3164ceb141e2.png)

When I open the generated srt file though the file is empty. I think it could be because the video does not have any silent parts. Im going to try a 90 min movie now.

**Comment by tawhidkhn63** [comment]
The 90 min file was processed in under 10 min and the srt file looks great! Is there a way to improve the accuracy of it?

**Comment by abhirooptalasila** [comment]
I'll try something with speaker diarization next month. It should help a bit. But the accuracy of the actual subtitles depends on how DeepSpeech performs on the audio. It works best with US English. What accent is the audio?

**Comment by tawhidkhn63** [comment]
My audio was an American guy speaking. Just one person. Would newer deepspeech scorer improve accuracy?

**Comment by abhirooptalasila** [comment]
Yes, it should.

**Comment by tawhidkhn63** [comment]
Could you tell me how to run the program on my computer's gtx 1050 gpu? I downloaded the deepspeech-gpu package but not sure what to do next. Is it the same commands to generate the subscript?

**Comment by abhirooptalasila** [comment]
The commands are the same. Refer to [this](https://deepspeech.readthedocs.io/en/latest/USING.html) for more info.

**Comment by FennyChhapia** [comment]
Hey @abhirooptalasila...

**Comment by FennyChhapia** [comment]
Hello @tawhidkhn63 @abhirooptalasila 

Can you please point me towards how to work in windows10 with this?
I mean a step by step guide would be grateful. I am quite new.

Thank you in advance.

**Comment by FennyChhapia** [comment]
So I troubleshoot a few things and reached till requirement installation.

![image](https://user-images.githubusercontent.com/76724007/104226962-a6698100-546e-11eb-9f3f-5e55c1530932.png)

Stuck here

**Comment by abhirooptalasila** [comment]
> 
> 
> I think DeepSpeech dependencies were updated. Just replace `numpy==1.18.1` with `numpy` in _requirements.txt_ and try again.

This should solve your issue.

**Comment by PreetM07** [comment]
Hi, Thanks for quick reply.

After changing to numpy in requirements.txt I got like this...
![image](https://user-images.githubusercontent.com/63149170/104269942-6c739b80-54bd-11eb-9e3c-6cbe0fd1856f.png)


Any suggestions?

**Comment by abhirooptalasila** [comment]
I just updated the requirements. Please clone the repo and try running it again.

**Comment by PreetM07** [comment]
![image](https://user-images.githubusercontent.com/63149170/104274818-b19ccb00-54c7-11eb-8f57-820ca7e7dee7.png)


After retrying with the changes...

**Comment by PreetM07** [comment]
changes made...

kiwisolver==1.2.0

replaced by...

kiwisolver


stuck at...
![image](https://user-images.githubusercontent.com/63149170/104274995-06404600-54c8-11eb-99a3-e50b91d103b6.png)

**Comment by PreetM07** [comment]
changed same for scipy

![image](https://user-images.githubusercontent.com/63149170/104275143-4c95a500-54c8-11eb-924d-5a9eb6074e61.png)

**Comment by abhirooptalasila** [comment]
I need the full stack trace to understand what's going on because you haven't given me any details of your environment. Use pastebin or use proper formatting while copying it here.

**Comment by PreetM07** [comment]
> I need the full stack trace to understand what's going on because you haven't given me any details of your environment. Use pastebin or use proper formatting while copying it here.

How do I do this? shall I divert the output of cmd to any file?
I am using
Intel core i5
windows 10 19041.685 version 2004 64 bit

**Comment by abhirooptalasila** [comment]
Yes, you can do that. Or just copy the output text and paste it here (with formatting)

**Comment by PreetM07** [comment]
[report.txt](https://github.com/abhirooptalasila/AutoSub/files/5800057/report.txt)


It just goes this much and not the errs

**Comment by abhirooptalasila** [comment]
This doesn't seem like the stacktrace. Check [this](https://stackoverflow.com/questions/58849799/running-setup-py-install-for-scikit-learn-error). It might be a version conflict if you're using anaconda. Did you make a virtual env before installing?

**Comment by PreetM07** [comment]
[stack_report_Format.txt](https://github.com/abhirooptalasila/AutoSub/files/5800146/stack_report_Format.txt)

whole console with format in the file...

I am not using anaconda but just the cmd
my python 3.9.1 installed with standard installation

yes I have enabled the virtual env before installing 
(I believe that's these 2 lines: 
python3 -m venv sub
$ source sub/bin/activate

which in windows goes like this:
python -m venv sub
.\sub\scripts\activate)

**Comment by abhirooptalasila** [comment]
There seems to be a version mismatch between pip and python. Or issue might be with Python 3.9. Try using 3.5. When you're running `python -m venv sub` make sure the PATH variable has the correct version of Python.

**Comment by PreetM07** [comment]
Experiments with python3.5 log
[ph3.5cmdlog_formatted.txt](https://github.com/abhirooptalasila/AutoSub/files/5800652/ph3.5cmdlog_formatted.txt)

**Comment by abhirooptalasila** [comment]
Definitely a problem with pip. Install 3.6 and upgrade pip outside the virtual env. Then install requirements. If you still face any problem, I've run out of ideas. Sorry :(

**Comment by PreetM07** [comment]
Ok...

So for windows users...
place this in the requirements file and it shall work with python 3.9 and integrated pip

cycler==0.10.0
Cython==0.29.21
numpy
deepspeech
joblib==0.16.0
kiwisolver
pydub==0.23.1
pyparsing==2.4.7
python-dateutil==2.8.1
scikit-learn
scipy
six==1.15.0
tqdm==4.44.1

**Comment by PreetM07** [comment]
Final output...

![image](https://user-images.githubusercontent.com/63149170/104356249-b8f8be80-5531-11eb-9738-afaf921cf3c6.png)



however the file is empty.
tried 2 times, both the times I got empty files.
Is there anything Unix dependent in the code? 
PS: I was trying with CUDA on but I think lib is not set properly.

**Comment by abhirooptalasila** [comment]
Yeah, CUDA isn't set up properly. Although, it's not necessary that using a GPU will give you quicker inference. Try using only the CPU package. Works pretty well.

**Comment by PreetM07** [comment]
Ok. Uninstalled the gpu pkg and worked with only cpu pkg. I read the doc of deepspeech, and they have not mentioned GPU support for windows10 with Intel X64.
However, I still am getting the file empty with a line saying...
"invalid scorer file. running inference only with model file"

![image](https://user-images.githubusercontent.com/63149170/104405348-c0948380-5582-11eb-95a9-8f55fd488521.png)

**Comment by PreetM07** [comment]
![image](https://user-images.githubusercontent.com/63149170/104406765-0c94f780-5586-11eb-9291-471abd06dfff.png)


Why I am getting empty srt?
I found that I was using light model for scorer, but I corrected it.
Still...

Any idea?

**Comment by PreetM07** [comment]
Ok...

I think it could be because of the relative paths used in the code?
It could be unix path style? Hardcoded? 
Because split audio files and srts are not going into the audio and output folders by default.
And when the code will be looking in the audio folder for processing further, but it wont find anything? Or maybe even not find the folder itslef!?
They are in the root... for me (D:\AutoSub\)

**Comment by abhirooptalasila** [comment]
Haha. Yes. I'm sorry I completely missed it. Try using absolute paths or place the video file in the repo root directory.

**Comment by PreetM07** [comment]
Yeah...
I think it's the issue.
I just placed the split files in the audio folder manually from earlier process.

And your code is now taking hell lot of time... (which actually is a good thing :D)

![image](https://user-images.githubusercontent.com/63149170/104408879-0bb29480-558b-11eb-8b16-9b8298133e25.png)

Will keep you posted... Cheers

**Comment by PreetM07** [comment]
Process is done.

Took almost 20-30 minutes for a 45 minute file.
srt is empty with following errors on console...

![image](https://user-images.githubusercontent.com/63149170/104412559-829f5b80-5592-11eb-8805-414a7b717a6e.png)

**Comment by abhirooptalasila** [comment]
Add `print("Limits: ", limits)` at Line 17 in _writeToFile.py_ [here](https://github.com/abhirooptalasila/AutoSub/blob/5444d9ab56b03c3d36eaedfaf9fcb9dfc63a3770/autosub/writeToFile.py#L17). 
And you'll have to replace `split("/")` with `split("\")` in _main.py_ since you're on Windows.

**Comment by PreetM07** [comment]
a glimpse to the generated srt

1
00:00:00,95 --> 00:00:01,95
and

2
00:00:09,75 --> 00:01:42,60
he eencawmprehensi etiennette

3
00:01:50,95 --> 00:01:56,50
i hear

4
00:02:02,50 --> 00:02:03,85
i knew

5
00:02:05,60 --> 00:02:07,0:
one

6
00:02:25,10 --> 00:02:27,40
with derision as

7
00:02:30,50 --> 00:02:33,05
and the profits curled there be darkness

8
00:02:33,40 --> 00:02:34,85
rosamond

9
00:02:35,60 --> 00:03:12,80
teetotalers at the line to either

10
00:03:13,80 --> 00:03:18,45
and you were going to drink

11
00:03:18,60 --> 00:04:01,0:
the man when he must we draw boswellister


Issue: srt is not is proper format. -- Transcription can be improved (?) -- Divisions of events can be clubbed later so that smaller parts don't float in individual events.

I have replaced split("/") to split("\\") everywhere in all the files of code.
I was trying this on a episode of a series.

Cheers...

**Comment by abhirooptalasila** [comment]
What's the accent of the audio?

**Comment by PreetM07** [comment]
> What's the accent of the audio?

It's US english
